name: Check if file exists
on: [pull_request]
jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "random3.txt"
